### PR TITLE
Location Logger Button added 

### LINKED ISSUE #70: Button to get location
Add a Button to Take Users Longitude and Latitude form it's browser location

### PR DESCRIPTION
**Pull request by Webby1015**
close #70 

## Checklist (Check all applicable boxes)

- [ ] My code adheres to the project's coding style.
- [ ] My changes require updates to the project's documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests have passed successfully.
- [ ] This PR does not contain any plagiarized content.
- [ ] The title of my pull request provides a brief description of the requested changes.

- [ ] I am contributing independently.
- [ ] I am contributing for Hacktoberfest 2023.

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
@Webby1015 it is kinda similar to the existing feature of show map ,where you get the lat and lng from the map .

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by ManishaSwain8** [comment]
@Webby1015 thankyou for your contribution !

**Comment by Webby1015** [comment]
Thank you

**Comment by Webby1015** [comment]
Would you like to contribute to my repository, I'm making a text editor

**Pull request merged**
