### PR TITLE
Multi-day weather forecast added and changed bg color to black.

### LINKED ISSUE #15: Weather Forecast: Provide a multi-day weather forecast for the selected location.
**Is your feature request related to a problem? Please describe.**
Yes, the current application provides current weather data, but users are also interested in having a multi-day weather forecast for the selected location.

**Describe the solution you'd like**
I would like to see a feature added to the application that provides a multi-day weather forecast for the selected location. This would allow users to plan for the upcoming days and make informed decisions based on the expected weather conditions.

**Describe alternatives you've considered**
One alternative could be integrating with a weather API that provides multi-day forecasts. However, it would be more convenient to have this feature built into the application to keep the user experience seamless.

**Additional context**
Adding a multi-day weather forecast feature would enhance the utility of the application and provide users with more comprehensive weather information. It aligns with the user's needs and expectations for planning purposes.

### PR DESCRIPTION
**Pull request by Abhii-07**
## Fixes Issue

#15 

## Proposed Changes

- [x] Created multi-day weather forecast

## Checklist (Check all applicable boxes)

- [x] My code adheres to the project's coding style.
- [x] My changes require updates to the project's documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests have passed successfully.
- [x] This PR does not contain any plagiarized content.
- [x] The title of my pull request provides a brief description of the requested changes.

- [x] I am contributing independently.
- [x] I am contributing for Hacktoberfest 2023.

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
@Abhii-07 any updates ,currently as 2 PRs are having conflicts so I have halt the process of assigning the issues to people .

**Comment by Abhii-07** [comment]
I think my PR should be merged first as it has just a feature update and people working on UI can then work on this.

**Comment by ManishaSwain8** [comment]
@Abhii-07 actually I have added a review comment please check it out,need some updation.

**Comment by Abhii-07** [comment]
I can't seem to find any review

**Comment by ManishaSwain8** [comment]
@Abhii-07 

Screenshot (211)

**Comment by Abhii-07** [comment]
Okay so now what I could do is close this PR and create another one as there are many conflicts since some more features are been added.

**Comment by Abhii-07** [comment]
Can you check now? I have added few imp comments. Maybe this would work

**Comment by ManishaSwain8** [comment]
@Abhii-07 every thing working fine with browser right ?

**Comment by Abhii-07** [comment]
I don't think there is any issue, you can merge.

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by ManishaSwain8** [comment]
Thankyou for your contribution @Abhii-07  !
I checked everything working fine , kudos to you !

Looking forward to more issues and collaborations.
If you learnt something from this repo make sure to ⭐ this repo.

Thankyou ,Happy coding !🚀

**Pull request merged**
