### PR TITLE
Feat: added toaster feature for all necessary error checks

### LINKED ISSUE #33: Add Toaster to give better user experience
**Is your feature request related to a problem? Please describe.**
Yes, the feature requested is to add a Toaster for the application so that the user can have a better user experience

**Describe the solution you'd like**
I would like to add a toast message when the data is fetched successfully from the api and vice versa when not fetched it will show a message to the user with a good ui giving the user a better experience for the app

@ManishaSwain8 if u can assign me this issue?

### PR DESCRIPTION
**Pull request by MurtazaShikari**
Have added the toaster for error handling and for successful search from API call
Also removed the unnecessary use of useEffect which was triggering API Call two times when changing units.
Have attached the video below.

## Video

https://github.com/ManishaSwain8/ReactToWeather/assets/114511800/74c15856-74fc-4f7c-89e5-c5b092dc95cb

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
@MurtazaShikari it looks like you have not updated before opening PR.
Make sure branch is updated and based on recent update in code ,you add your features.

**Comment by MurtazaShikari** [comment]
@ManishaSwain8 how should I fix this issue I am new to open source contribution can you help me out?

**Comment by ManishaSwain8** [comment]
@MurtazaShikari no problem will provide you some steps that you need to keep in mind before opening PR.

**Comment by ManishaSwain8** [comment]
@MurtazaShikari as you are new to this ,
If you are comfortable then click on resolve conflict button and check what changes you did and what is the conflicts without tampering existing code changes that may lead to failure of certain features.
If you are not able to resolve it ,make sure to watch some YT videos /docs .

If yet you are confused ,close the PR and add your features to the updated code ,and open new PR

**Comment by MurtazaShikari** [comment]
@ManishaSwain8 have resolved the conflicts on Github associated to this PR.
Thanks for your help!

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by ManishaSwain8** [comment]
Thankyou for your contribution @MurtazaShikari  !

Looking forward to more issues and collaborations.
If you learnt something from this repo make sure to ⭐ this repo.

Thankyou ,Happy coding !🚀

**Pull request merged**
