### PR TITLE
feat:footer_component

### LINKED ISSUE #64: Footer section in the bottom of the web-application .
**Is your feature request related to a problem? Please describe.**
there is only a black screen at the bottom of the page and want to make and update a good footer section that will help the user contact the owner of the project for such type of web applications. 

**Describe the solution you'd like**
will add a simple footer section in the bottom ,

I have 2  options :
1. a simple footer in which I will mention created by ❤️by @ManishaSwain8 
2. Footer section with all the contact us ,about us and etc .

**Describe alternatives you've considered**
or mention a new and alternative way for the footer section , I will update that also.

Pls assign me for the above mentioned changes 
and after completing up the I will raise up the PR ASAP.

Label it with Hacktoberfest tag.

### PR DESCRIPTION
**Pull request by abhay-raj19**
Closes #64 

## Fixes Issue
 As suggested under issue #64 , added up a footer component with the same pattern as suggested by you and also added up the same content as you commented out in the issue .

## Checklist (Check all applicable boxes)

- [✅] My code adheres to the project's coding style.
- [✅] My changes require updates to the project's documentation.
- [✅] I have updated the documentation accordingly.
- [✅] All new and existing tests have passed successfully.
- [✅] This PR does not contain any plagiarized content.
- [✅] The title of my pull request provides a brief description of the requested changes.

- [✅] I am contributing independently.
- [✅] I am contributing for Hacktoberfest 2023.

## Screenshots

image

## Reviewer Notes
Pls do review up the changes and do suggest the features to be added into it.

@ManishaSwain8  Pls label it with `Hactobefest-accepted ` and ` Hacktoberfest `.

### CODE REVIEW

**Comment by abhay-raj19** [comment]
@ManishaSwain8 pls do review up the changes as listed under #64  .

**Comment by ManishaSwain8** [comment]
@abhay-raj19 you can add some more content to it , like about us,contact us ,with logo (sky colored icon that you can see in the tab)with title though footer is not req for this project ,still you can add some more content to it .

**Comment by abhay-raj19** [comment]
@ManishaSwain8 now pls do review it , if it is fine merge it into main codebase and pls do label it with `hacktoberfest-accepted` label

**Comment by ManishaSwain8** [comment]
@abhay-raj19 you have removed some of the CSS that is affecting other elements too .
1. Button color of "Show map " is removed.
2. preloader has been moved to corner .

**Comment by abhay-raj19** [comment]
@ManishaSwain8 now pls do review it

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by ManishaSwain8** [comment]
@abhay-raj19  thankyou for your contribution !

**Pull request merged**
