### PR TITLE
fix(setunit): updated the code to render changes when unit is changed

### LINKED ISSUE #2: 🔥Temperature doesn't covert while toggling.
Whenever a person toggles on the options to convert to Celsius,Kelvin,etc the temperature doesn't convert. Make sure to use your api and more contributing process are present in readme.md.

Feel free to work on this bug !
Happy coding !😃

### PR DESCRIPTION
**Pull request by IrfanSalim**
Closes #2  

## Proposed Changes

Updated the code to rerender the weather data after making another API call when the user changes the unit.
Updated the CSS to contain the weather component within the viewport

## Checklist (Check all applicable boxes)

- [x] My code adheres to the project's coding style.
- [ ] My changes require updates to the project's documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests have passed successfully.
- [x] This PR does not contain any plagiarized content.
- [x] The title of my pull request provides a brief description of the requested changes.

- [ ] I am contributing independently.
- [x] I am contributing for Hacktoberfest 2023.

https://github.com/ManishaSwain8/ReactToWeather/assets/109443065/fe0ed2d6-159a-4cf2-89ce-1b4c22fe62a4

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
@IrfanSalim  can you please make a sort video on what changes you did (no audio req) , so that it will be easier to get reviewed .

**Comment by ManishaSwain8** [comment]
And spelling error correction is assigned to someone else, lets give chance to everyone to contribute  , just change the spelling to as it is .😂

**Comment by IrfanSalim** [comment]
> And spelling error correction is assigned to someone else, lets give chance to everyone to contribute , just change the spelling to as it is .😂

I would have to make the changes and push again 😢

**Comment by ManishaSwain8** [comment]
Cool ! will review it 

> > And spelling error correction is assigned to someone else, lets give chance to everyone to contribute , just change the spelling to as it is .😂
> 
> I would have to make the changes and push again 😢

Not req, it's ok ....well everything looks cool, will review it.

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by IrfanSalim** [comment]
> Cool ! will review it
> 
> > > And spelling error correction is assigned to someone else, lets give chance to everyone to contribute , just change the spelling to as it is .😂
> > 
> > 
> > I would have to make the changes and push again 😢
> 
> Not req, it's ok ....well everything looks cool, will review it.

**Sigh**
Thankss 😁

**Comment by ManishaSwain8** [comment]
Thankyou for your contribution  @IrfanSalim  !

Looking forward to more issues and collaborations.
If you learnt something from this repo make sure to ⭐ this repo.

Thankyou ,Happy coding !🚀

**Pull request merged**
