### PR TITLE
Adjust breakpoints for buttons "Get Weather" and "Show Forecast", City input alignment and width:auto of block elements.

### PR DESCRIPTION
**Pull request by gabrielpoetaa**
Hi, 
Buttons are fixed now, didn't need to adjust any breakpoint, just wrap both buttons in a div container. I also fixed the alignment of City input by removing a set ml-4 from the original code, screenshot provided. Finally, I've noticed some block elements were declared with width:auto, which is redundant since all block elements are width:auto by default. Went ahead and change it to 100% or removed them for code cleanliness.

 
Screen Shot 2023-10-20 at 11 26 00 PM

Hope these changes increase the visual impact of this project  😀

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
@gabrielpoetaa I think you have removed the preloader css , as it is appearing at the corner ,

Screenshot (233)

As well as the spacing is also req between dropdown option and input field

**Comment by gabrielpoetaa** [comment]
Hi, 
sorry about that. Whenever I try to change the input elements (removing the ml-4, for example) the app.css file brakes and the pre loader is pushed to the corner. I tried loading tailwind with app.css being the input, but then the voice icon breaks. 
Screen Shot 2023-10-21 at 10 21 41 AM


I couldn't figure out why. If you have any tips please share because I'd like to learn. In the meantime, the original issue (buttons "Get Weather" and "Show Forecast") are fixed. They no longer bleed out of the page in smaller viewports. Can I close this PR and open a new one with the original issue? 

Thank you!

**Comment by gabrielpoetaa** [comment]
Hi, 
sorry about that. I was running tailwind along with the react file so whenever I made a change on the home component the app.css would trigger and break the pre-loader style. Its fixed now. I copied over the original files from both app.css and index.css so now it works just fine. 

In order to fix the space between the drop-down menu and city input I didn't just deleted the ml-4 as I've done before. Now I've included a breakpoint on the city input, so it has the necessary spaces when it's in wider viewports (ml-4 applied) and keeps the alignment when in smaller screens.

Video where it shows the functionality - > https://streamable.com/2izzpg

Hope it works now! 😀

**Comment by ManishaSwain8** [comment]
@gabrielpoetaa not a problem ! 
Will review it soon  : )

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by ManishaSwain8** [comment]
@gabrielpoetaa thankyou for your contribution !

**Pull request merged**
