### PR TITLE
feature/tempConverterAdded [Hardik2972]

### PR DESCRIPTION
**Pull request by Hardik2972**
### I add the temp coverter feature here is the video link of my changes -
https://drive.google.com/file/d/1L4y2K_L1zdP2-lx0yX0Ge_I4VCc6GYgR/view?usp=sharing

## Checklist (Check all applicable boxes)

- [X] My code adheres to the project's coding style.
- [ ] My changes require updates to the project's documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests have passed successfully.
- [X] This PR does not contain any plagiarized content.
- [X] The title of my pull request provides a brief description of the requested changes.

- [ ] I am contributing independently.
- [X] I am contributing for Hacktoberfest 2023.

## Screenshots

Screenshot 2023-10-24 122715

## Reviewer Notes
 I used react-router-dom package for navigation so we need to install before run
`npm i react-router-dom`

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
Sorry to inform you @Hardik2972 ,
 As per this repo ,if PR is opened without assigned issue , then PR will not get merged.

**Comment by Hardik2972** [comment]
If no one resolved the issue then please consider my PR before the end of hactoberfest end.

**Comment by ManishaSwain8** [comment]
No worries all PR will be taken care of before 31st.

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by ManishaSwain8** [comment]
Thankyou @Hardik2972 for your contribution and patience !

**Pull request merged**
