### PR TITLE
Added a feature to get weather details by entering geolocation #8 

### PR DESCRIPTION
**Pull request by uddiptojana10**
Closes issue https://github.com/ManishaSwain8/ReactToWeather/issues/8
Video:

https://github.com/ManishaSwain8/ReactToWeather/assets/117717963/51ef26ff-ab33-4a02-8fb2-4c6de03549f1

I have placed the dropdown menu near the top right while also styling it according to the theme of the website.

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
@uddiptojana10 any updates ,currently I have halted assigning issue due to some conflict PRs,

**Comment by uddiptojana10** [comment]
you can close my previous PR (it was creating some problems)and merge this, if you like the video i have attached.

**Comment by ManishaSwain8** [comment]
@uddiptojana10 actually I have added a review on updation , will send you SS

**Comment by ManishaSwain8** [comment]
@uddiptojana10  if you still getting confused about reviews let me know

**Comment by uddiptojana10** [comment]
@ManishaSwain8 okay i'll fix it

**Comment by ManishaSwain8** [comment]
All the best ! keep it up !

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by uddiptojana10** [comment]
@ManishaSwain8 i have added back all the comments

**Comment by ManishaSwain8** [comment]
Yup got it ,every thing working fine with browser right ?

will be adding vercel deployment soon so that to view updates .

**Comment by uddiptojana10** [comment]
yep, everything fine with browser.

**Comment by ManishaSwain8** [comment]
Thankyou for your contribution @uddiptojana10  !
Finally it done, kudos to you !
Looking forward to more issues and collaborations.
If you learnt something from this repo make sure to ⭐ this repo.

Thankyou ,Happy coding !🚀

**Pull request merged**
