### PR TITLE
added loader

### LINKED ISSUE #23: Add Loader for Data Fetching
**Is your feature request related to a problem? Please describe.**
The current user interface lacks a loader, making it difficult for users to know when data is being fetched.

**Describe the solution you'd like**
I would like to add a loader that is visible while data is being fetched. This loader will provide visual feedback to users, indicating that the application is actively retrieving data.

**Describe alternatives you've considered**
One alternative would be to rely solely on the user interface without a loader. However, this can lead to confusion and a less intuitive user experience.

**Additional context**
Currently, when a user submits a request for weather data, there is no visual indication that the data is being fetched. Adding a loader will improve the user experience by clearly indicating the ongoing data retrieval process.

### PR DESCRIPTION
**Pull request by Shiba-Tatsuya**
## Fixes Issue
Closes #23

## Checklist (Check all applicable boxes)

- [x] My code adheres to the project's coding style.
- [x] The title of my pull request provides a brief description of the requested changes.

## Labels

- [x] Hacktoberfest

## Potential Impact on Existing Code

No significant impact on existing code.

## Video

https://github.com/ManishaSwain8/ReactToWeather/assets/75966408/3762fcf7-0f70-4226-9157-e95b9ebfd9ed

### CODE REVIEW

**Comment by ManishaSwain8** [comment]
@Shiba-Tatsuya can you make loader bit small ?

**Comment by Shiba-Tatsuya** [comment]
sure

**Comment by Shiba-Tatsuya** [comment]
<Loader type="bubble-top" bgColor={"#6709AB"} title={""} size={80} /> if you still want to change size you can change by size parameter

**Review by ManishaSwain8 — APPROVED** [review]

**Comment by ManishaSwain8** [comment]
Thankyou for your contribution @Shiba-Tatsuya  !

Tips: Rather than js-loader you can you can use react-loader/spinner ,it has some beautiful loaders with additional functionalities.

Looking forward to more issues and collaborations.
If you learnt something from this repo make sure to ⭐ this repo.

Thankyou ,Happy coding !🚀

**Pull request merged**
